# Generated by Django 5.0.1 on 2024-01-30 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harryPotterCG', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
