# Generated by Django 5.0.1 on 2024-02-06 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='credits',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
