# Generated by Django 5.0.1 on 2024-02-08 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_useraccount_credits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='credits',
        ),
    ]
