# Generated by Django 5.0.1 on 2024-02-10 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_remove_useraccount_credits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='date_joined',
        ),
    ]
